# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


pool: 
 name: Default
 demands:
  - Agent.Name -equals SPIDERMAN

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo "Run Selenium Tests"
      :: mvn clean test
      mvn clean test -DargLine=-javaagent:"C:\\Parasoft-packages\\parasoft_selenic_2024.1.0\\selenic_agent.jar"=captureDom=true,selfHealing=true -DsuiteXmlFiles=testng.xml
      java -jar "C:\\Parasoft-packages\\parasoft_selenic_2024.1.0\\selenic_analyzer.jar"

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junitreports/TEST-*.xml'